# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  firefox = {
    pname = "firefox";
    version = "132.0.1";
    src = fetchurl {
      url = "https://archive.mozilla.org/pub/firefox/releases/132.0.1/source/firefox-132.0.1.source.tar.xz";
      sha256 = "sha256-XAMbVywdpyZnfi/5e2rVp+OyM4em/DljORy1YvgKXkg=";
    };
  };
  zen-browser = {
    pname = "zen-browser";
    version = "1.0.1-a.19";
    src = fetchFromGitHub {
      owner = "zen-browser";
      repo = "desktop";
      rev = "1.0.1-a.19";
      fetchSubmodules = true;
      sha256 = "sha256-+eehLsnQoWapkSKo3zWFxaz6N68BryK1XsmSk48zbbk=";
    };
  };
}
