# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  firefox = {
    pname = "firefox";
    version = "136.0.1";
    src = fetchurl {
      url = "https://archive.mozilla.org/pub/firefox/releases/136.0.1/source/firefox-136.0.1.source.tar.xz";
      sha256 = "sha256-TxK9z6pycffysYq403ensivpXqAfEeGOHr93lT4yIbY=";
    };
  };
  zen-browser = {
    pname = "zen-browser";
    version = "1.9.1b";
    src = fetchFromGitHub {
      owner = "zen-browser";
      repo = "desktop";
      rev = "1.9.1b";
      fetchSubmodules = true;
      sha256 = "sha256-fg6HD85iZOU2o1F27kWONIKtrArG1HqYAGk4qldYBp4=";
    };
  };
}
