# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  firefox = {
    pname = "firefox";
    version = "136.0.2";
    src = fetchurl {
      url = "https://archive.mozilla.org/pub/firefox/releases/136.0.2/source/firefox-136.0.2.source.tar.xz";
      sha256 = "sha256-Uxh8noRUP3eDblV8Kin5UjixEed5FUIX3y7ZtQ3b8gA=";
    };
  };
  firefox-l10n = {
    pname = "firefox-l10n";
    version = "last-sync";
    src = fetchFromGitHub {
      owner = "mozilla-l10n";
      repo = "firefox-l10n";
      rev = "last-sync";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = true;
      sha256 = "sha256-DOAm6SY0VI3okOLmpgDNb58NKFUuSln9p3fM2AhaQOo=";
    };
  };
  zen-browser = {
    pname = "zen-browser";
    version = "1.9.1b";
    src = fetchFromGitHub {
      owner = "zen-browser";
      repo = "desktop";
      rev = "1.9.1b";
      fetchSubmodules = true;
      sha256 = "sha256-fg6HD85iZOU2o1F27kWONIKtrArG1HqYAGk4qldYBp4=";
    };
  };
}
