# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  firefox-sources = {
    pname = "firefox-sources";
    version = "131.0.3";
    src = fetchurl {
      url = "https://archive.mozilla.org/pub/firefox/releases/131.0.3/source/firefox-131.0.3.source.tar.xz";
      sha256 = "sha256-en3z+Xc3RT76okPKnbr5XQ8PgzxdyK+stXBO4W7wYNA=";
    };
  };
  mozilla-l10n = {
    pname = "mozilla-l10n";
    version = "9d639cd79d6b73081fadb3474dd7d73b89732e7b";
    src = fetchFromGitHub {
      owner = "mozilla-l10n";
      repo = "firefox-l10n";
      rev = "9d639cd79d6b73081fadb3474dd7d73b89732e7b";
      fetchSubmodules = false;
      sha256 = "sha256-+2JCaPp+c2BRM60xFCeY0pixIyo2a3rpTPaSt1kTfDw=";
    };
  };
  surfer = {
    pname = "surfer";
    version = "50af7094ede6e9f0910f010c531f8447876a6464";
    src = fetchFromGitHub {
      owner = "zen-browser";
      repo = "surfer";
      rev = "50af7094ede6e9f0910f010c531f8447876a6464";
      fetchSubmodules = false;
      sha256 = "sha256-wmAWg6hoICNHfoXJifYFHmyFQS6H22u3GSuRW4alexw=";
    };
  };
  zen-browser-sources = {
    pname = "zen-browser-sources";
    version = "1.0.1-a.12";
    src = fetchFromGitHub {
      owner = "zen-browser";
      repo = "desktop";
      rev = "1.0.1-a.12";
      fetchSubmodules = true;
      sha256 = "sha256-/13rgdbvLVd/MWWXOuY7H2YH7KDJczrSwI9H3kIHHM8=";
    };
  };
}
